# Generated by Django 3.1.1 on 2022-12-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.CharField(blank=True, max_length=250, null=True, verbose_name='Card')),
            ],
        ),
    ]
